name: yandex_disk
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
#  path: ^1.7.0
  dio: ^4.0.0-beta7
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner:
  pedantic: ^1.11.0
  test: ^1.16.5
  freezed: ^0.14.1
  json_serializable: