name: yandex_disk
description: The library for integration with Yandex.Disk via HTTP REST API.
version: 0.1.2
homepage: https://the-english-breaker.ru

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  dio: ^4.0.0
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner:
  pedantic: ^1.11.0
  test: ^1.16.5
  freezed: ^0.14.1
  json_serializable: